-- =====================================================
-- Example Application: Pot Hole Observation System
-- =====================================================
-- PostGIS is installed in the postgis schema by core Civic OS scripts
-- and is accessible via search_path
-- NOTE: Requires Civic OS v0.15.0+ (Status Type System)

-- =====================================================
-- STATUS TYPE SYSTEM CONFIGURATION
-- Uses centralized metadata.statuses for workflow state tracking (v0.15.0+)
-- =====================================================

INSERT INTO metadata.status_types (entity_type, display_name, description) VALUES
  ('issue', 'Issue', 'Status values for pothole issues'),
  ('work_package', 'Work Package', 'Status values for pothole work packages')
ON CONFLICT (entity_type) DO NOTHING;

INSERT INTO metadata.statuses (entity_type, display_name, color, sort_order, is_initial, is_terminal) VALUES
  ('issue', 'New', '#3B82F6', 1, TRUE, FALSE),
  ('issue', 'Verification', '#8B5CF6', 2, FALSE, FALSE),
  ('issue', 'Re-estimate', '#F59E0B', 3, FALSE, FALSE),
  ('issue', 'Repair Queue', '#F97316', 4, FALSE, FALSE),
  ('issue', 'Batched for Quote', '#06B6D4', 5, FALSE, FALSE),
  ('issue', 'Bid Accepted', '#22C55E', 6, FALSE, FALSE),
  ('issue', 'Completed', '#6B7280', 7, FALSE, TRUE),
  ('issue', 'Duplicate', '#9CA3AF', 8, FALSE, TRUE)
ON CONFLICT DO NOTHING;

INSERT INTO metadata.statuses (entity_type, display_name, color, sort_order, is_initial, is_terminal) VALUES
  ('work_package', 'New', '#3B82F6', 1, TRUE, FALSE),
  ('work_package', 'Competitive', '#F59E0B', 2, FALSE, FALSE),
  ('work_package', 'Awarded', '#22C55E', 3, FALSE, TRUE),
  ('work_package', 'Not Selected', '#6B7280', 4, FALSE, TRUE)
ON CONFLICT DO NOTHING;

-- Bid table
CREATE TABLE "public"."Bid" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"owner" UUID NOT NULL,
	"work_start_date" DATE NOT NULL,
	"work_end_date" DATE NOT NULL,
	"work_package" BIGINT NOT NULL,
	"total_cost" MONEY NOT NULL,
	"company_email" email_address NOT NULL,
	"contact_phone" phone_number
);

-- Issue table
CREATE TABLE "public"."Issue" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"status" INT NOT NULL DEFAULT get_initial_status('issue'),
	"created_user" UUID NOT NULL DEFAULT current_user_id(),
	"work_package" BIGINT,
	"location" postgis.geography(Point, 4326),
	"contact_email" email_address,
	"contact_phone" phone_number
);

-- WorkDetail table
CREATE TABLE "public"."WorkDetail" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"issue" BIGINT NOT NULL,
	"added_by" UUID NOT NULL
);

-- WorkPackage table
CREATE TABLE "public"."WorkPackage" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" CHARACTER VARYING NOT NULL,
	"quote_due_date" TIMESTAMP WITH TIME ZONE NOT NULL,
	"status" INT DEFAULT get_initial_status('work_package'),
	"cost" MONEY
);

-- Tag table (for M:M relationship example)
CREATE TABLE "public"."Tag" (
	"id" SERIAL PRIMARY KEY,
	"display_name" VARCHAR(50) NOT NULL UNIQUE,
	"color" hex_color NOT NULL DEFAULT '#3B82F6',
	"description" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ
);

-- Issue_Tags junction table (many-to-many)
-- This table will be auto-detected as a junction and hidden from menu
-- Uses composite primary key (PostgreSQL best practice for junction tables)
CREATE TABLE "public"."issue_tags" (
	"issue_id" BIGINT NOT NULL,
	"tag_id" INT NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (issue_id, tag_id)
);

-- Create indexes
CREATE UNIQUE INDEX "Bid_pkey" ON public."Bid" USING btree (id);
CREATE UNIQUE INDEX "Issue_pkey" ON public."Issue" USING btree (id);
CREATE UNIQUE INDEX "WorkDetail_pkey" ON public."WorkDetail" USING btree (id);
CREATE UNIQUE INDEX "WorkPackage_pkey" ON public."WorkPackage" USING btree (id);

-- Indexes for email/phone fields (for search and filtering)
CREATE INDEX "idx_issue_contact_email" ON public."Issue" USING btree (contact_email);
CREATE INDEX "idx_bid_company_email" ON public."Bid" USING btree (company_email);

-- Add primary key constraints
ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_pkey" PRIMARY KEY USING INDEX "Bid_pkey";
ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_pkey" PRIMARY KEY USING INDEX "Issue_pkey";
ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_pkey" PRIMARY KEY USING INDEX "WorkDetail_pkey";
ALTER TABLE "public"."WorkPackage" ADD CONSTRAINT "WorkPackage_pkey" PRIMARY KEY USING INDEX "WorkPackage_pkey";

-- Add foreign key constraints
ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_owner_fkey"
  FOREIGN KEY (owner) REFERENCES metadata.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."Bid" VALIDATE CONSTRAINT "Bid_owner_fkey";

ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_work_package_fkey"
  FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) NOT VALID;
ALTER TABLE "public"."Bid" VALIDATE CONSTRAINT "Bid_work_package_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_created_user_fkey"
  FOREIGN KEY (created_user) REFERENCES metadata.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_created_user_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_status_fkey"
  FOREIGN KEY (status) REFERENCES metadata.statuses(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_status_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_work_package_fkey"
  FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_work_package_fkey";

ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_added_by_fkey"
  FOREIGN KEY (added_by) REFERENCES metadata.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."WorkDetail" VALIDATE CONSTRAINT "WorkDetail_added_by_fkey";

ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_issue_fkey"
  FOREIGN KEY (issue) REFERENCES "Issue"(id) NOT VALID;
ALTER TABLE "public"."WorkDetail" VALIDATE CONSTRAINT "WorkDetail_issue_fkey";

ALTER TABLE "public"."WorkPackage" ADD CONSTRAINT "WorkPackage_status_fkey"
  FOREIGN KEY (status) REFERENCES metadata.statuses(id) NOT VALID;
ALTER TABLE "public"."WorkPackage" VALIDATE CONSTRAINT "WorkPackage_status_fkey";

ALTER TABLE "public"."issue_tags" ADD CONSTRAINT "issue_tags_issue_fkey"
  FOREIGN KEY (issue_id) REFERENCES "Issue"(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."issue_tags" VALIDATE CONSTRAINT "issue_tags_issue_fkey";

ALTER TABLE "public"."issue_tags" ADD CONSTRAINT "issue_tags_tag_fkey"
  FOREIGN KEY (tag_id) REFERENCES "Tag"(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."issue_tags" VALIDATE CONSTRAINT "issue_tags_tag_fkey";

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Bid" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Issue" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkDetail" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkPackage" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Tag" TO web_anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE "public"."issue_tags" TO web_anon, authenticated;

-- Grant sequence permissions
GRANT USAGE ON SEQUENCE "public"."Bid_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."Issue_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkDetail_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkPackage_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."Tag_id_seq" TO web_anon, authenticated;

-- Enable Row Level Security
ALTER TABLE "public"."Bid" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Issue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkDetail" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkPackage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."issue_tags" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Bid
CREATE POLICY "Bid: read permission" ON "public"."Bid"
  FOR SELECT
  TO PUBLIC
  USING (has_permission('Bid', 'read'));

CREATE POLICY "Bid: create permission" ON "public"."Bid"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (has_permission('Bid', 'create'));

CREATE POLICY "Bid: update permission" ON "public"."Bid"
  FOR UPDATE
  TO PUBLIC
  USING (has_permission('Bid', 'update'))
  WITH CHECK (has_permission('Bid', 'update'));

CREATE POLICY "Bid: delete permission" ON "public"."Bid"
  FOR DELETE
  TO PUBLIC
  USING (has_permission('Bid', 'delete'));

-- RLS Policies for Issue
CREATE POLICY "Issue: read permission" ON "public"."Issue"
  FOR SELECT
  TO PUBLIC
  USING (has_permission('Issue', 'read'));

CREATE POLICY "Issue: create permission" ON "public"."Issue"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (has_permission('Issue', 'create'));

CREATE POLICY "Issue: update permission" ON "public"."Issue"
  FOR UPDATE
  TO PUBLIC
  USING (has_permission('Issue', 'update'))
  WITH CHECK (has_permission('Issue', 'update'));

CREATE POLICY "Issue: delete permission" ON "public"."Issue"
  FOR DELETE
  TO PUBLIC
  USING (has_permission('Issue', 'delete'));

-- RLS Policies for WorkDetail
CREATE POLICY "WorkDetail: read permission" ON "public"."WorkDetail"
  FOR SELECT
  TO PUBLIC
  USING (has_permission('WorkDetail', 'read'));

CREATE POLICY "WorkDetail: create permission" ON "public"."WorkDetail"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (has_permission('WorkDetail', 'create'));

CREATE POLICY "WorkDetail: update permission" ON "public"."WorkDetail"
  FOR UPDATE
  TO PUBLIC
  USING (has_permission('WorkDetail', 'update'))
  WITH CHECK (has_permission('WorkDetail', 'update'));

CREATE POLICY "WorkDetail: delete permission" ON "public"."WorkDetail"
  FOR DELETE
  TO PUBLIC
  USING (has_permission('WorkDetail', 'delete'));

-- RLS Policies for WorkPackage
CREATE POLICY "WorkPackage: read permission" ON "public"."WorkPackage"
  FOR SELECT
  TO PUBLIC
  USING (has_permission('WorkPackage', 'read'));

CREATE POLICY "WorkPackage: create permission" ON "public"."WorkPackage"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (has_permission('WorkPackage', 'create'));

CREATE POLICY "WorkPackage: update permission" ON "public"."WorkPackage"
  FOR UPDATE
  TO PUBLIC
  USING (has_permission('WorkPackage', 'update'))
  WITH CHECK (has_permission('WorkPackage', 'update'));

CREATE POLICY "WorkPackage: delete permission" ON "public"."WorkPackage"
  FOR DELETE
  TO PUBLIC
  USING (has_permission('WorkPackage', 'delete'));

-- RLS Policies for Tag
CREATE POLICY "Tag: read permission" ON "public"."Tag"
  FOR SELECT
  TO PUBLIC
  USING (has_permission('Tag', 'read'));

CREATE POLICY "Tag: create permission" ON "public"."Tag"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (has_permission('Tag', 'create'));

CREATE POLICY "Tag: update permission" ON "public"."Tag"
  FOR UPDATE
  TO PUBLIC
  USING (has_permission('Tag', 'update'))
  WITH CHECK (has_permission('Tag', 'update'));

CREATE POLICY "Tag: delete permission" ON "public"."Tag"
  FOR DELETE
  TO PUBLIC
  USING (has_permission('Tag', 'delete'));

-- RLS Policies for issue_tags (junction table)
CREATE POLICY "issue_tags: read permission" ON "public"."issue_tags"
  FOR SELECT
  TO PUBLIC
  USING (has_permission('issue_tags', 'read'));

CREATE POLICY "issue_tags: create permission" ON "public"."issue_tags"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (has_permission('issue_tags', 'create'));

CREATE POLICY "issue_tags: delete permission" ON "public"."issue_tags"
  FOR DELETE
  TO PUBLIC
  USING (has_permission('issue_tags', 'delete'));

-- Apply timestamp triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Bid"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."Bid"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Issue"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."Issue"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkDetail"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."WorkDetail"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkPackage"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."WorkPackage"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Tag"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."Tag"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."issue_tags"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

-- Computed field function to expose geography as text for PostgREST
CREATE OR REPLACE FUNCTION public.location_text("Issue")
RETURNS text AS $$
  SELECT postgis.ST_AsText($1.location);
$$ LANGUAGE SQL STABLE;

GRANT EXECUTE ON FUNCTION public.location_text("Issue") TO web_anon, authenticated;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';
