# Copyright (C) 2023-2025 Civic OS, L3C
# AGPL-3.0-or-later

apiVersion: apps/v1
kind: Deployment
metadata:
  name: civic-os-swagger-ui
  namespace: civic-os
  labels:
    app: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
      - name: swagger-ui
        image: swaggerapi/swagger-ui:latest
        ports:
        - containerPort: 8080
          name: http
        env:
        # Point Swagger UI to PostgREST's public OpenAPI spec
        # IMPORTANT: Use the public API URL, not internal service URL
        # This is because Swagger UI runs in the browser, not in-cluster
        - name: API_URL
          valueFrom:
            configMapKeyRef:
              name: civic-os-config
              key: SWAGGER_API_URL
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: civic-os-swagger-ui
  namespace: civic-os
  labels:
    app: swagger-ui
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: swagger-ui
