// Copyright (C) 2023-2026 Civic OS, L3C. AGPL-3.0-or-later.

import chalk from 'chalk';
import type { LLMResponse, CategorizedSQL, SQLCategory } from '../providers/provider.js';
import type { SafetyResult } from '../safety/validator.js';
import { blocksToScript } from './sql-extractor.js';
import { writeFile } from 'node:fs/promises';

const CATEGORY_COLORS: Record<SQLCategory, (s: string) => string> = {
  ddl: chalk.cyan,
  indexes: chalk.blue,
  status: chalk.magenta,
  category: chalk.magenta,
  metadata: chalk.green,
  validations: chalk.green,
  grants: chalk.yellow,
  rls: chalk.yellow,
  permissions: chalk.yellow,
  functions: chalk.cyan,
  triggers: chalk.blue,
  notify: chalk.gray,
  adr: chalk.gray,
};

/** Format LLM response for terminal display. */
export function formatTerminalOutput(response: LLMResponse, safety: SafetyResult): string {
  const lines: string[] = [];

  // Header
  lines.push(chalk.bold(`\nSchema Assistant — ${response.model}`));
  lines.push(chalk.dim(`${response.usage.inputTokens} input / ${response.usage.outputTokens} output tokens`));
  lines.push(chalk.dim(`Cost: $${response.cost.totalCost.toFixed(4)} | Latency: ${(response.latencyMs / 1000).toFixed(1)}s`));
  if (response.cost.cacheSavings) {
    lines.push(chalk.dim(`Cache savings: $${response.cost.cacheSavings.toFixed(4)}`));
  }

  // Reasoning
  if (response.reasoning) {
    lines.push('');
    lines.push(chalk.bold('Reasoning:'));
    lines.push(response.reasoning);
  }

  // Safety summary
  lines.push('');
  if (safety.safe) {
    lines.push(chalk.green.bold('✓ Safety check passed'));
  } else {
    lines.push(chalk.red.bold('✗ Safety check failed'));
  }
  for (const warn of safety.warnings) {
    lines.push(chalk.yellow(`  ⚠ ${warn.reason}`));
    lines.push(chalk.dim(`    ${truncate(warn.statement, 100)}`));
  }
  for (const err of safety.errors) {
    lines.push(chalk.red(`  ✗ ${err.reason}`));
    lines.push(chalk.dim(`    ${truncate(err.statement, 100)}`));
  }

  // SQL blocks
  lines.push('');
  lines.push(chalk.bold(`SQL Output (${response.sqlBlocks.length} blocks):`));
  lines.push('');

  for (const block of response.sqlBlocks) {
    const colorFn = CATEGORY_COLORS[block.category] ?? chalk.white;
    lines.push(colorFn(`── [${block.category.toUpperCase()}] ${block.description} ──`));
    lines.push(block.sql);
    lines.push('');
  }

  return lines.join('\n');
}

/** Write combined SQL to a file. */
export async function writeOutputFile(response: LLMResponse, filePath: string): Promise<void> {
  const header = [
    `-- Generated by Civic OS Schema Assistant`,
    `-- Model: ${response.model}`,
    `-- Tokens: ${response.usage.inputTokens} in / ${response.usage.outputTokens} out`,
    `-- Cost: $${response.cost.totalCost.toFixed(4)}`,
    `-- Date: ${new Date().toISOString()}`,
    '',
    'BEGIN;',
    '',
  ].join('\n');

  const footer = '\nCOMMIT;\n';
  const script = blocksToScript(response.sqlBlocks);
  await writeFile(filePath, header + script + footer, 'utf-8');
}

/** Write the raw LLM response (including reasoning/thinking) to a file. */
export async function writeRawResponse(response: LLMResponse, filePath: string): Promise<void> {
  const header = [
    `Model: ${response.model}`,
    `Tokens: ${response.usage.inputTokens} in / ${response.usage.outputTokens} out`,
    `Cost: $${response.cost.totalCost.toFixed(4)}`,
    `Latency: ${(response.latencyMs / 1000).toFixed(1)}s`,
    `Date: ${new Date().toISOString()}`,
    '',
    '--- REASONING ---',
    response.reasoning || '(none)',
    '',
    '--- RAW RESPONSE ---',
    response.rawResponse,
  ].join('\n');
  await writeFile(filePath, header, 'utf-8');
}

function truncate(s: string, maxLen: number): string {
  const oneLine = s.replace(/\n/g, ' ').trim();
  if (oneLine.length <= maxLen) return oneLine;
  return oneLine.substring(0, maxLen - 3) + '...';
}
