
-- =============================================================================================================
-- CIVIC OS APPLICATION: EXAMPLE
-- =============================================================================================================

-- Generated: Fri Oct 24 17:51:45 EDT 2025
-- Example: example
-- 
-- This file contains application-specific tables, permissions, and mock data for the example example.
-- 
-- PREREQUISITES:
--   1. Civic OS core schema must be deployed first via Sqitch migrations
--   2. PostgreSQL with PostGIS extension
--   3. Authenticator role must be created
--
-- To deploy core Civic OS schema:
--   docker run --rm -e PGRST_DB_URI="your-connection-string" \
--     ghcr.io/civic-os/migrations:latest deploy
--
-- After core deployment, run this SQL file to set up the example application.

-- =============================================================================================================
-- APPLICATION-SPECIFIC SCRIPTS
-- =============================================================================================================


-- Source: 01_pot_hole_schema.sql

-- =====================================================
-- Example Application: Pot Hole Observation System
-- =====================================================
-- PostGIS is installed in the postgis schema by core Civic OS scripts
-- and is accessible via search_path

-- Bid table
CREATE TABLE "public"."Bid" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"owner" UUID NOT NULL,
	"work_start_date" DATE NOT NULL,
	"work_end_date" DATE NOT NULL,
	"work_package" BIGINT NOT NULL,
	"total_cost" MONEY NOT NULL,
	"company_email" email_address NOT NULL,
	"contact_phone" phone_number
);

-- Issue table
CREATE TABLE "public"."Issue" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"status" BIGINT NOT NULL DEFAULT '1'::BIGINT,
	"created_user" UUID NOT NULL DEFAULT public.current_user_id(),
	"work_package" BIGINT,
	"location" postgis.geography(Point, 4326),
	"contact_email" email_address,
	"contact_phone" phone_number
);

-- IssueStatus table
CREATE TABLE "public"."IssueStatus" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"display_name" CHARACTER VARYING NOT NULL
);

-- WorkDetail table
CREATE TABLE "public"."WorkDetail" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"issue" BIGINT NOT NULL,
	"added_by" UUID NOT NULL
);

-- WorkPackage table
CREATE TABLE "public"."WorkPackage" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" CHARACTER VARYING NOT NULL,
	"quote_due_date" TIMESTAMP WITH TIME ZONE NOT NULL,
	"status" BIGINT,
	"cost" MONEY
);

-- WorkPackageStatus table
CREATE TABLE "public"."WorkPackageStatus" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"display_name" CHARACTER VARYING NOT NULL
);

-- Tag table (for M:M relationship example)
CREATE TABLE "public"."Tag" (
	"id" SERIAL PRIMARY KEY,
	"display_name" VARCHAR(50) NOT NULL UNIQUE,
	"color" hex_color NOT NULL DEFAULT '#3B82F6',
	"description" TEXT,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMPTZ
);

-- Issue_Tags junction table (many-to-many)
-- This table will be auto-detected as a junction and hidden from menu
-- Uses composite primary key (PostgreSQL best practice for junction tables)
CREATE TABLE "public"."issue_tags" (
	"issue_id" BIGINT NOT NULL,
	"tag_id" INT NOT NULL,
	"created_at" TIMESTAMPTZ NOT NULL DEFAULT NOW(),
	PRIMARY KEY (issue_id, tag_id)
);

-- Create indexes
CREATE UNIQUE INDEX "Bid_pkey" ON public."Bid" USING btree (id);
CREATE UNIQUE INDEX "IssueStatus_display_name_key" ON public."IssueStatus" USING btree (display_name);
CREATE UNIQUE INDEX "IssueStatus_pkey" ON public."IssueStatus" USING btree (id);
CREATE UNIQUE INDEX "Issue_pkey" ON public."Issue" USING btree (id);
CREATE UNIQUE INDEX "WorkDetail_pkey" ON public."WorkDetail" USING btree (id);
CREATE UNIQUE INDEX "WorkPackageStatus_pkey" ON public."WorkPackageStatus" USING btree (id);
CREATE UNIQUE INDEX "WorkPackage_pkey" ON public."WorkPackage" USING btree (id);

-- Indexes for email/phone fields (for search and filtering)
CREATE INDEX "idx_issue_contact_email" ON public."Issue" USING btree (contact_email);
CREATE INDEX "idx_bid_company_email" ON public."Bid" USING btree (company_email);

-- Add primary key constraints
ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_pkey" PRIMARY KEY USING INDEX "Bid_pkey";
ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_pkey" PRIMARY KEY USING INDEX "Issue_pkey";
ALTER TABLE "public"."IssueStatus" ADD CONSTRAINT "IssueStatus_pkey" PRIMARY KEY USING INDEX "IssueStatus_pkey";
ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_pkey" PRIMARY KEY USING INDEX "WorkDetail_pkey";
ALTER TABLE "public"."WorkPackage" ADD CONSTRAINT "WorkPackage_pkey" PRIMARY KEY USING INDEX "WorkPackage_pkey";
ALTER TABLE "public"."WorkPackageStatus" ADD CONSTRAINT "WorkPackageStatus_pkey" PRIMARY KEY USING INDEX "WorkPackageStatus_pkey";

-- Add foreign key constraints
ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_owner_fkey"
  FOREIGN KEY (owner) REFERENCES metadata.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."Bid" VALIDATE CONSTRAINT "Bid_owner_fkey";

ALTER TABLE "public"."Bid" ADD CONSTRAINT "Bid_work_package_fkey"
  FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) NOT VALID;
ALTER TABLE "public"."Bid" VALIDATE CONSTRAINT "Bid_work_package_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_created_user_fkey"
  FOREIGN KEY (created_user) REFERENCES metadata.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_created_user_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_status_fkey"
  FOREIGN KEY (status) REFERENCES "IssueStatus"(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_status_fkey";

ALTER TABLE "public"."Issue" ADD CONSTRAINT "Issue_work_package_fkey"
  FOREIGN KEY (work_package) REFERENCES "WorkPackage"(id) NOT VALID;
ALTER TABLE "public"."Issue" VALIDATE CONSTRAINT "Issue_work_package_fkey";

ALTER TABLE "public"."IssueStatus" ADD CONSTRAINT "IssueStatus_display_name_key"
  UNIQUE USING INDEX "IssueStatus_display_name_key";

ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_added_by_fkey"
  FOREIGN KEY (added_by) REFERENCES metadata.civic_os_users(id) NOT VALID;
ALTER TABLE "public"."WorkDetail" VALIDATE CONSTRAINT "WorkDetail_added_by_fkey";

ALTER TABLE "public"."WorkDetail" ADD CONSTRAINT "WorkDetail_issue_fkey"
  FOREIGN KEY (issue) REFERENCES "Issue"(id) NOT VALID;
ALTER TABLE "public"."WorkDetail" VALIDATE CONSTRAINT "WorkDetail_issue_fkey";

ALTER TABLE "public"."WorkPackage" ADD CONSTRAINT "WorkPackage_status_fkey"
  FOREIGN KEY (status) REFERENCES "WorkPackageStatus"(id) NOT VALID;
ALTER TABLE "public"."WorkPackage" VALIDATE CONSTRAINT "WorkPackage_status_fkey";

ALTER TABLE "public"."issue_tags" ADD CONSTRAINT "issue_tags_issue_fkey"
  FOREIGN KEY (issue_id) REFERENCES "Issue"(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."issue_tags" VALIDATE CONSTRAINT "issue_tags_issue_fkey";

ALTER TABLE "public"."issue_tags" ADD CONSTRAINT "issue_tags_tag_fkey"
  FOREIGN KEY (tag_id) REFERENCES "Tag"(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."issue_tags" VALIDATE CONSTRAINT "issue_tags_tag_fkey";

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Bid" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Issue" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."IssueStatus" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkDetail" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkPackage" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."WorkPackageStatus" TO web_anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "public"."Tag" TO web_anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE "public"."issue_tags" TO web_anon, authenticated;

-- Grant sequence permissions
GRANT USAGE ON SEQUENCE "public"."Bid_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."Issue_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."IssueStatus_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkDetail_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkPackage_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."WorkPackageStatus_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."Tag_id_seq" TO web_anon, authenticated;

-- Enable Row Level Security
ALTER TABLE "public"."Bid" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Issue" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."IssueStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkDetail" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkPackage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."WorkPackageStatus" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."Tag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."issue_tags" ENABLE ROW LEVEL SECURITY;

-- RLS Policies for Bid
CREATE POLICY "Bid: read permission" ON "public"."Bid"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('Bid', 'read'));

CREATE POLICY "Bid: create permission" ON "public"."Bid"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('Bid', 'create'));

CREATE POLICY "Bid: update permission" ON "public"."Bid"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('Bid', 'update'))
  WITH CHECK (public.has_permission('Bid', 'update'));

CREATE POLICY "Bid: delete permission" ON "public"."Bid"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('Bid', 'delete'));

-- RLS Policies for Issue
CREATE POLICY "Issue: read permission" ON "public"."Issue"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('Issue', 'read'));

CREATE POLICY "Issue: create permission" ON "public"."Issue"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('Issue', 'create'));

CREATE POLICY "Issue: update permission" ON "public"."Issue"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('Issue', 'update'))
  WITH CHECK (public.has_permission('Issue', 'update'));

CREATE POLICY "Issue: delete permission" ON "public"."Issue"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('Issue', 'delete'));

-- RLS Policies for IssueStatus
CREATE POLICY "IssueStatus: read permission" ON "public"."IssueStatus"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('IssueStatus', 'read'));

CREATE POLICY "IssueStatus: create permission" ON "public"."IssueStatus"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('IssueStatus', 'create'));

CREATE POLICY "IssueStatus: update permission" ON "public"."IssueStatus"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('IssueStatus', 'update'))
  WITH CHECK (public.has_permission('IssueStatus', 'update'));

CREATE POLICY "IssueStatus: delete permission" ON "public"."IssueStatus"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('IssueStatus', 'delete'));

-- RLS Policies for WorkDetail
CREATE POLICY "WorkDetail: read permission" ON "public"."WorkDetail"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('WorkDetail', 'read'));

CREATE POLICY "WorkDetail: create permission" ON "public"."WorkDetail"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('WorkDetail', 'create'));

CREATE POLICY "WorkDetail: update permission" ON "public"."WorkDetail"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('WorkDetail', 'update'))
  WITH CHECK (public.has_permission('WorkDetail', 'update'));

CREATE POLICY "WorkDetail: delete permission" ON "public"."WorkDetail"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('WorkDetail', 'delete'));

-- RLS Policies for WorkPackage
CREATE POLICY "WorkPackage: read permission" ON "public"."WorkPackage"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('WorkPackage', 'read'));

CREATE POLICY "WorkPackage: create permission" ON "public"."WorkPackage"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('WorkPackage', 'create'));

CREATE POLICY "WorkPackage: update permission" ON "public"."WorkPackage"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('WorkPackage', 'update'))
  WITH CHECK (public.has_permission('WorkPackage', 'update'));

CREATE POLICY "WorkPackage: delete permission" ON "public"."WorkPackage"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('WorkPackage', 'delete'));

-- RLS Policies for WorkPackageStatus
CREATE POLICY "WorkPackageStatus: read permission" ON "public"."WorkPackageStatus"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('WorkPackageStatus', 'read'));

CREATE POLICY "WorkPackageStatus: create permission" ON "public"."WorkPackageStatus"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('WorkPackageStatus', 'create'));

CREATE POLICY "WorkPackageStatus: update permission" ON "public"."WorkPackageStatus"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('WorkPackageStatus', 'update'))
  WITH CHECK (public.has_permission('WorkPackageStatus', 'update'));

CREATE POLICY "WorkPackageStatus: delete permission" ON "public"."WorkPackageStatus"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('WorkPackageStatus', 'delete'));

-- RLS Policies for Tag
CREATE POLICY "Tag: read permission" ON "public"."Tag"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('Tag', 'read'));

CREATE POLICY "Tag: create permission" ON "public"."Tag"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('Tag', 'create'));

CREATE POLICY "Tag: update permission" ON "public"."Tag"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('Tag', 'update'))
  WITH CHECK (public.has_permission('Tag', 'update'));

CREATE POLICY "Tag: delete permission" ON "public"."Tag"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('Tag', 'delete'));

-- RLS Policies for issue_tags (junction table)
CREATE POLICY "issue_tags: read permission" ON "public"."issue_tags"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('issue_tags', 'read'));

CREATE POLICY "issue_tags: create permission" ON "public"."issue_tags"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('issue_tags', 'create'));

CREATE POLICY "issue_tags: delete permission" ON "public"."issue_tags"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('issue_tags', 'delete'));

-- Apply timestamp triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Bid"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."Bid"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Issue"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."Issue"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."IssueStatus"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkDetail"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."WorkDetail"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkPackage"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."WorkPackage"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."WorkPackageStatus"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."Tag"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."Tag"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."issue_tags"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

-- Computed field function to expose geography as text for PostgREST
CREATE OR REPLACE FUNCTION public.location_text("Issue")
RETURNS text AS $$
  SELECT postgis.ST_AsText($1.location);
$$ LANGUAGE SQL STABLE;

GRANT EXECUTE ON FUNCTION public.location_text("Issue") TO web_anon, authenticated;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';

-- Source: 02_validation_examples.sql

-- =====================================================
-- Validation Examples for Pot Hole Domain
-- =====================================================
-- This script demonstrates all validation types supported by Civic OS.
-- Run after 01_pot_hole_schema.sql

-- Add new fields to existing tables for validation demonstrations
ALTER TABLE public."Issue" ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE public."Issue" ADD COLUMN IF NOT EXISTS severity_level INT;

-- =====================================================
-- Backend Enforcement: CHECK Constraints
-- =====================================================

-- Example 1 & 2: MIN and MAX validation - Bid total_cost
ALTER TABLE public."Bid"
  DROP CONSTRAINT IF EXISTS bid_total_cost_positive,
  DROP CONSTRAINT IF EXISTS bid_total_cost_reasonable;

ALTER TABLE public."Bid"
  ADD CONSTRAINT bid_total_cost_positive CHECK (total_cost > 0::money),
  ADD CONSTRAINT bid_total_cost_reasonable CHECK (total_cost <= 100000::money);

-- Example 3: MINLENGTH validation - Issue description
ALTER TABLE public."Issue"
  DROP CONSTRAINT IF EXISTS description_min_length;

ALTER TABLE public."Issue"
  ADD CONSTRAINT description_min_length CHECK (char_length(description) >= 10 OR description IS NULL);

-- Example 4: MAXLENGTH validation - Tag name
ALTER TABLE public."Tag"
  DROP CONSTRAINT IF EXISTS tag_name_max_length;

ALTER TABLE public."Tag"
  ADD CONSTRAINT tag_name_max_length CHECK (char_length(display_name) <= 50);

-- Example 5: PATTERN validation - Phone number (enforced via pattern, documented in metadata)
-- Note: PostgreSQL CHECK constraints can use regex with ~ operator, but we'll handle this in frontend

-- Example 6: MIN/MAX range - Severity level (1-5 scale)
ALTER TABLE public."Issue"
  DROP CONSTRAINT IF EXISTS severity_valid_range;

ALTER TABLE public."Issue"
  ADD CONSTRAINT severity_valid_range CHECK (severity_level >= 1 AND severity_level <= 5 OR severity_level IS NULL);

-- Example 7: WorkPackage cost positive
ALTER TABLE public."WorkPackage"
  DROP CONSTRAINT IF EXISTS cost_positive;

ALTER TABLE public."WorkPackage"
  ADD CONSTRAINT cost_positive CHECK (cost > 0::money OR cost IS NULL);

-- =====================================================
-- Frontend UX: Validation Metadata
-- =====================================================

-- Example 1: MIN validation - Bid total_cost must be positive
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('Bid', 'total_cost', 'min', '0.01', 'Bid total cost must be greater than zero', 1)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- Example 2: MAX validation - Bid total_cost cap
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('Bid', 'total_cost', 'max', '100000', 'Bid total cost cannot exceed $100,000', 2)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- Example 3: MINLENGTH validation - Issue description
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('Issue', 'description', 'minLength', '10', 'Description must be at least 10 characters', 1)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- Example 4: MAXLENGTH validation - Tag name
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('Tag', 'display_name', 'maxLength', '50', 'Tag name cannot exceed 50 characters', 1)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- Example 5: PATTERN validation - Phone number (10 digits, no formatting)
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('Issue', 'contact_phone', 'pattern', '^\d{10}$', 'Phone number must be exactly 10 digits (no dashes or spaces)', 1)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- Example 6a: MIN validation - Severity level minimum
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('Issue', 'severity_level', 'min', '1', 'Severity must be between 1 (low) and 5 (critical)', 1)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- Example 6b: MAX validation - Severity level maximum
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('Issue', 'severity_level', 'max', '5', 'Severity must be between 1 (low) and 5 (critical)', 2)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- Example 7: WorkPackage cost positive
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES ('WorkPackage', 'cost', 'min', '0.01', 'Cost must be greater than zero', 1)
ON CONFLICT (table_name, column_name, validation_type) DO UPDATE
  SET validation_value = EXCLUDED.validation_value,
      error_message = EXCLUDED.error_message,
      sort_order = EXCLUDED.sort_order;

-- =====================================================
-- CHECK Constraint Error Message Mapping
-- =====================================================

-- Map backend CHECK constraints to user-friendly messages
INSERT INTO metadata.constraint_messages (constraint_name, table_name, column_name, error_message)
VALUES
  ('bid_total_cost_positive', 'Bid', 'total_cost', 'Bid total cost must be greater than zero'),
  ('bid_total_cost_reasonable', 'Bid', 'total_cost', 'Bid total cost cannot exceed $100,000'),
  ('description_min_length', 'Issue', 'description', 'Description must be at least 10 characters'),
  ('severity_valid_range', 'Issue', 'severity_level', 'Severity must be between 1 (low) and 5 (critical)'),
  ('tag_name_max_length', 'Tag', 'display_name', 'Tag name cannot exceed 50 characters'),
  ('cost_positive', 'WorkPackage', 'cost', 'Cost must be greater than zero')
ON CONFLICT (constraint_name) DO UPDATE
  SET table_name = EXCLUDED.table_name,
      column_name = EXCLUDED.column_name,
      error_message = EXCLUDED.error_message;

-- =====================================================
-- Property Display Metadata (for new fields)
-- =====================================================

-- Add friendly labels and descriptions for new validation example fields
INSERT INTO metadata.properties (table_name, column_name, display_name, description, sort_order)
VALUES
  ('Issue', 'description', 'Description', 'Detailed description of the issue (min 10 characters)', 2),
  ('Issue', 'contact_email', 'Contact Email', 'Email address of the person reporting this issue', 3),
  ('Issue', 'contact_phone', 'Contact Phone', 'Phone number to contact about this issue (10 digits)', 4),
  ('Issue', 'severity_level', 'Severity Level', 'Urgency rating from 1 (low) to 5 (critical)', 5),
  ('Bid', 'company_email', 'Company Email', 'Primary email address for the bidding company', 5),
  ('Bid', 'contact_phone', 'Contact Phone', 'Phone number for bid inquiries', 6)
ON CONFLICT (table_name, column_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- Source: 03_pot_hole_data.sql

-- =====================================================
-- Pot Hole Observation System - Seed Data
-- =====================================================

-- Seed IssueStatus data
INSERT INTO "public"."IssueStatus" ("id", "created_at", "display_name") VALUES
  ('1', '2024-12-14 20:58:32.638955+00', 'New'),
  ('2', '2024-12-14 21:02:44.44308+00', 'Verification'),
  ('3', '2024-12-14 21:04:23.589205+00', 'Re-estimate'),
  ('4', '2024-12-14 21:05:50.549546+00', 'Repair Queue'),
  ('5', '2024-12-14 21:06:05.12863+00', 'Batched for Quote'),
  ('6', '2024-12-14 21:06:15.078694+00', 'Bid Accepted'),
  ('7', '2024-12-14 21:06:24.374326+00', 'Completed'),
  ('8', '2024-12-14 21:06:28.683431+00', 'Duplicate');

-- Seed WorkPackageStatus data
INSERT INTO "public"."WorkPackageStatus" ("id", "created_at", "display_name") VALUES
  ('2', '2024-12-14 21:29:56.694099+00', 'New'),
  ('3', '2024-12-14 21:30:12.753812+00', 'Competitive'),
  ('4', '2024-12-14 21:30:47.936383+00', 'Awarded'),
  ('5', '2024-12-14 21:30:53.014772+00', 'Not Selected');

-- Seed Tag data (for many-to-many relationship example)
INSERT INTO public."Tag" (display_name, color, description) VALUES
  ('Urgent', '#EF4444', 'Requires immediate attention'),
  ('Intersection', '#F59E0B', 'Located at an intersection'),
  ('School Zone', '#EAB308', 'Near a school'),
  ('Sidewalk', '#3B82F6', 'Sidewalk-related issue'),
  ('Road Surface', '#6366F1', 'Road surface damage'),
  ('Drainage', '#06B6D4', 'Water drainage problem'),
  ('Lighting', '#8B5CF6', 'Street lighting issue'),
  ('Signage', '#EC4899', 'Traffic sign or street sign');

-- Metadata: Configure display name and description for Tag entity
INSERT INTO metadata.entities (table_name, display_name, description, sort_order) VALUES
  ('Tag', 'Tags', 'Categorization tags for issues', 60)
ON CONFLICT (table_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';

-- Source: 04_pot_hole_permissions.sql

-- =====================================================
-- Pot Hole Observation System - Permissions
-- =====================================================
-- This script creates RBAC permissions for the example application tables
-- Customize this for your own application tables

-- Create permissions for all pot hole tables
INSERT INTO metadata.permissions (table_name, permission) VALUES
  ('Bid', 'read'),
  ('Bid', 'create'),
  ('Bid', 'update'),
  ('Bid', 'delete'),
  ('Issue', 'read'),
  ('Issue', 'create'),
  ('Issue', 'update'),
  ('Issue', 'delete'),
  ('IssueStatus', 'read'),
  ('IssueStatus', 'create'),
  ('IssueStatus', 'update'),
  ('IssueStatus', 'delete'),
  ('WorkDetail', 'read'),
  ('WorkDetail', 'create'),
  ('WorkDetail', 'update'),
  ('WorkDetail', 'delete'),
  ('WorkPackage', 'read'),
  ('WorkPackage', 'create'),
  ('WorkPackage', 'update'),
  ('WorkPackage', 'delete'),
  ('WorkPackageStatus', 'read'),
  ('WorkPackageStatus', 'create'),
  ('WorkPackageStatus', 'update'),
  ('WorkPackageStatus', 'delete'),
  ('Tag', 'read'),
  ('Tag', 'create'),
  ('Tag', 'update'),
  ('Tag', 'delete'),
  ('issue_tags', 'read'),
  ('issue_tags', 'create'),
  ('issue_tags', 'update'),
  ('issue_tags', 'delete')
ON CONFLICT (table_name, permission) DO NOTHING;

-- Grant read permission to all roles for all tables
INSERT INTO metadata.permission_roles (permission_id, role_id)
SELECT p.id, r.id
FROM metadata.permissions p
CROSS JOIN metadata.roles r
WHERE p.table_name IN ('Bid', 'Issue', 'IssueStatus', 'WorkDetail', 'WorkPackage', 'WorkPackageStatus', 'Tag', 'issue_tags')
  AND p.permission = 'read'
  AND r.display_name IN ('anonymous', 'user', 'editor', 'admin')
ON CONFLICT DO NOTHING;

-- Grant create/update to authenticated users (user, editor, admin)
INSERT INTO metadata.permission_roles (permission_id, role_id)
SELECT p.id, r.id
FROM metadata.permissions p
CROSS JOIN metadata.roles r
WHERE p.table_name IN ('Bid', 'Issue', 'IssueStatus', 'WorkDetail', 'WorkPackage', 'WorkPackageStatus', 'Tag', 'issue_tags')
  AND p.permission IN ('create', 'update')
  AND r.display_name IN ('user', 'editor', 'admin')
ON CONFLICT DO NOTHING;

-- Grant delete to editors and admins only
INSERT INTO metadata.permission_roles (permission_id, role_id)
SELECT p.id, r.id
FROM metadata.permissions p
CROSS JOIN metadata.roles r
WHERE p.table_name IN ('Bid', 'Issue', 'IssueStatus', 'WorkDetail', 'WorkPackage', 'WorkPackageStatus', 'Tag', 'issue_tags')
  AND p.permission = 'delete'
  AND r.display_name IN ('editor', 'admin')
ON CONFLICT DO NOTHING;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';

-- Source: 05_add_text_search.sql

-- =====================================================
-- Add Text Search to Issue Table
-- =====================================================
-- This script demonstrates how to enable full-text search on an entity
-- by adding a civic_os_text_search column and configuring search_fields

-- Add the generated tsvector column for full-text search
ALTER TABLE "public"."Issue"
  ADD COLUMN civic_os_text_search tsvector
  GENERATED ALWAYS AS (
    to_tsvector('english', coalesce(display_name, ''))
  ) STORED;

-- Create GIN index for fast text search
CREATE INDEX "Issue_text_search_idx"
  ON "public"."Issue"
  USING GIN (civic_os_text_search);

-- Configure search fields in metadata
-- This tells the frontend which fields are included in the search
INSERT INTO metadata.entities (table_name, display_name, search_fields, sort_order)
VALUES ('Issue', 'Issues', ARRAY['display_name'], 10)
ON CONFLICT (table_name) DO UPDATE
  SET search_fields = EXCLUDED.search_fields;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';

-- Source: 06_add_fk_indexes.sql

-- =====================================================
-- Add Indexes for Foreign Key Columns
-- =====================================================
--
-- PostgreSQL does NOT automatically index foreign key columns
-- (only the referenced PRIMARY KEY columns are indexed).
--
-- For inverse relationships to perform well, we need indexes
-- on all foreign key columns to avoid full table scans.
--
-- Without these indexes, queries like "SELECT * FROM Issue WHERE status = 1"
-- will perform a full table scan instead of an index lookup.

-- Issue table FK indexes
CREATE INDEX IF NOT EXISTS idx_issues_status ON "Issue"(status);
CREATE INDEX IF NOT EXISTS idx_issues_created_user ON "Issue"(created_user);
CREATE INDEX IF NOT EXISTS idx_issues_work_package ON "Issue"(work_package);

-- Bid table FK indexes
CREATE INDEX IF NOT EXISTS idx_bids_owner ON "Bid"(owner);
CREATE INDEX IF NOT EXISTS idx_bids_work_package ON "Bid"(work_package);

-- WorkDetail table FK indexes
CREATE INDEX IF NOT EXISTS idx_work_details_issue ON "WorkDetail"(issue);
CREATE INDEX IF NOT EXISTS idx_work_details_added_by ON "WorkDetail"(added_by);

-- WorkPackage table FK indexes
CREATE INDEX IF NOT EXISTS idx_work_packages_status ON "WorkPackage"(status);

-- Many-to-Many junction table indexes
-- CRITICAL: These indexes are required for:
-- 1. Fast junction table queries (Issue -> Tags)
-- 2. Inverse relationship queries (Tags -> Issues)
-- 3. Performant many-to-many operations
CREATE INDEX IF NOT EXISTS idx_issue_tags_issue_id ON "issue_tags"(issue_id);
CREATE INDEX IF NOT EXISTS idx_issue_tags_tag_id ON "issue_tags"(tag_id);

-- Index comments
COMMENT ON INDEX idx_issues_status IS 'Optimize inverse relationship queries for IssueStatus -> Issue';
COMMENT ON INDEX idx_issues_created_user IS 'Optimize inverse relationship queries for civic_os_users -> Issue (created by)';
COMMENT ON INDEX idx_issues_work_package IS 'Optimize inverse relationship queries for WorkPackage -> Issue';
COMMENT ON INDEX idx_bids_owner IS 'Optimize inverse relationship queries for civic_os_users -> Bid (owner)';
COMMENT ON INDEX idx_bids_work_package IS 'Optimize inverse relationship queries for WorkPackage -> Bid';
COMMENT ON INDEX idx_work_details_issue IS 'Optimize inverse relationship queries for Issue -> WorkDetail';
COMMENT ON INDEX idx_work_details_added_by IS 'Optimize inverse relationship queries for civic_os_users -> WorkDetail (added by)';
COMMENT ON INDEX idx_work_packages_status IS 'Optimize inverse relationship queries for WorkPackageStatus -> WorkPackage';
COMMENT ON INDEX idx_issue_tags_issue_id IS 'Optimize M:M junction queries for Issue -> Tags';
COMMENT ON INDEX idx_issue_tags_tag_id IS 'Optimize M:M junction queries for Tags -> Issues';

-- Source: 07_add_file_fields.sql

-- =====================================================
-- Add File Storage Examples to Pot Hole Schema
-- =====================================================
-- Demonstrates FileImage and FilePDF property types with validations

-- Add photo field to Issue table (for FileImage example)
ALTER TABLE "public"."Issue"
  ADD COLUMN "photo" UUID REFERENCES metadata.files(id);

-- Add report_pdf field to WorkPackage table (for FilePDF example)
ALTER TABLE "public"."WorkPackage"
  ADD COLUMN "report_pdf" UUID REFERENCES metadata.files(id);

-- Create index on file FK columns
CREATE INDEX idx_issue_photo ON "public"."Issue"(photo);
CREATE INDEX idx_workpackage_report_pdf ON "public"."WorkPackage"(report_pdf);

-- Add validation metadata for Issue.photo (image files only, max 5MB)
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES
  ('Issue', 'photo', 'fileType', 'image/*', 'Only image files are allowed', 1),
  ('Issue', 'photo', 'maxFileSize', '5242880', 'File size must not exceed 5 MB', 2);

-- Add validation metadata for WorkPackage.report_pdf (PDF files only, max 10MB)
INSERT INTO metadata.validations (table_name, column_name, validation_type, validation_value, error_message, sort_order)
VALUES
  ('WorkPackage', 'report_pdf', 'fileType', 'application/pdf', 'Only PDF files are allowed', 1),
  ('WorkPackage', 'report_pdf', 'maxFileSize', '10485760', 'File size must not exceed 10 MB', 2);

-- Add property metadata for custom display names
INSERT INTO metadata.properties (table_name, column_name, display_name, description, sort_order)
VALUES
  ('Issue', 'photo', 'Photo', 'Upload a photo of the pothole or issue', 50),
  ('WorkPackage', 'report_pdf', 'Final Report', 'Upload the final work package report (PDF)', 60)
ON CONFLICT (table_name, column_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';

-- =============================================================================================================
-- SETUP COMPLETE
-- =============================================================================================================

-- Next steps:
-- 1. Review this SQL file
-- 2. Execute against your hosted database:
--    psql 'postgresql://user:password@host:port/dbname?sslmode=require' -f pothole.sql

