
-- =============================================================================================================
-- CIVIC OS APPLICATION: BROADER IMPACTS
-- =============================================================================================================

-- Generated: Fri Oct 24 17:52:19 EDT 2025
-- Example: broader-impacts
-- 
-- This file contains application-specific tables, permissions, and mock data for the broader-impacts example.
-- 
-- PREREQUISITES:
--   1. Civic OS core schema must be deployed first via Sqitch migrations
--   2. PostgreSQL with PostGIS extension
--   3. Authenticator role must be created
--
-- To deploy core Civic OS schema:
--   docker run --rm -e PGRST_DB_URI="your-connection-string" \
--     ghcr.io/civic-os/migrations:latest deploy
--
-- After core deployment, run this SQL file to set up the broader-impacts application.

-- =============================================================================================================
-- APPLICATION-SPECIFIC SCRIPTS
-- =============================================================================================================


-- Source: 01_broader_impacts_schema.sql

-- =====================================================
-- Broader Impacts Tracking System - Schema
-- =====================================================
-- This schema tracks organizations, contacts, projects, and their broader impact categories
-- PostGIS is installed in the postgis schema by core Civic OS scripts and is accessible via search_path

-- =====================================================
-- CORE ENTITY TABLES
-- =====================================================

-- Organization Types (lookup table)
CREATE TABLE "public"."organization_types" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL UNIQUE,
	"description" TEXT
);

-- Organizations
CREATE TABLE "public"."organizations" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"organization_type_id" BIGINT NOT NULL,
	"address" TEXT,
	"phone" phone_number,
	"email" email_address,
	"website" TEXT,
	"description" TEXT
);

-- Contacts
CREATE TABLE "public"."contacts" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"first_name" TEXT NOT NULL,
	"last_name" TEXT NOT NULL,
	"display_name" TEXT GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
	"email" email_address,
	"phone" phone_number,
	"organization_id" BIGINT,
	"title" TEXT,
	"description" TEXT
);

-- Project Statuses (lookup table)
CREATE TABLE "public"."project_statuses" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL UNIQUE,
	"description" TEXT
);

-- Interest Centers
CREATE TABLE "public"."interest_centers" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"description" TEXT
);

-- Projects
CREATE TABLE "public"."projects" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"description" TEXT,
	"organization_id" BIGINT NOT NULL,
	"interest_center_id" BIGINT,
	"start_date" DATE,
	"end_date" DATE,
	"status_id" BIGINT
);

-- Broader Impact Categories
CREATE TABLE "public"."broader_impact_categories" (
	"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	"updated_at" TIMESTAMP WITH TIME ZONE,
	"display_name" TEXT NOT NULL,
	"description" TEXT
);

-- =====================================================
-- JUNCTION TABLES (Many-to-Many Relationships)
-- =====================================================
-- These tables use composite primary keys and will be auto-detected as junction tables
-- and hidden from the menu. The M:M editor will appear on Detail pages.

-- Organizations <-> Broader Impact Categories
CREATE TABLE "public"."organization_broader_impact_categories" (
	"organization_id" BIGINT NOT NULL,
	"broader_impact_category_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	PRIMARY KEY (organization_id, broader_impact_category_id)
);

-- Contacts <-> Projects
CREATE TABLE "public"."contact_projects" (
	"contact_id" BIGINT NOT NULL,
	"project_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	PRIMARY KEY (contact_id, project_id)
);

-- Contacts <-> Broader Impact Categories
CREATE TABLE "public"."contact_broader_impact_categories" (
	"contact_id" BIGINT NOT NULL,
	"broader_impact_category_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	PRIMARY KEY (contact_id, broader_impact_category_id)
);

-- Projects <-> Broader Impact Categories
CREATE TABLE "public"."project_broader_impact_categories" (
	"project_id" BIGINT NOT NULL,
	"broader_impact_category_id" BIGINT NOT NULL,
	"created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
	PRIMARY KEY (project_id, broader_impact_category_id)
);

-- =====================================================
-- INDEXES
-- =====================================================

-- Unique indexes for primary keys
CREATE UNIQUE INDEX "organization_types_pkey" ON public."organization_types" USING btree (id);
CREATE UNIQUE INDEX "organizations_pkey" ON public."organizations" USING btree (id);
CREATE UNIQUE INDEX "contacts_pkey" ON public."contacts" USING btree (id);
CREATE UNIQUE INDEX "project_statuses_pkey" ON public."project_statuses" USING btree (id);
CREATE UNIQUE INDEX "interest_centers_pkey" ON public."interest_centers" USING btree (id);
CREATE UNIQUE INDEX "projects_pkey" ON public."projects" USING btree (id);
CREATE UNIQUE INDEX "broader_impact_categories_pkey" ON public."broader_impact_categories" USING btree (id);

-- Foreign key indexes (CRITICAL for performance and inverse relationships)
CREATE INDEX "idx_organizations_organization_type_id" ON public."organizations"(organization_type_id);
CREATE INDEX "idx_contacts_organization_id" ON public."contacts"(organization_id);
CREATE INDEX "idx_projects_organization_id" ON public."projects"(organization_id);
CREATE INDEX "idx_projects_interest_center_id" ON public."projects"(interest_center_id);
CREATE INDEX "idx_projects_status_id" ON public."projects"(status_id);

-- Junction table indexes (both FKs for efficient lookups in both directions)
CREATE INDEX "idx_org_bic_organization_id" ON public."organization_broader_impact_categories"(organization_id);
CREATE INDEX "idx_org_bic_category_id" ON public."organization_broader_impact_categories"(broader_impact_category_id);
CREATE INDEX "idx_contact_projects_contact_id" ON public."contact_projects"(contact_id);
CREATE INDEX "idx_contact_projects_project_id" ON public."contact_projects"(project_id);
CREATE INDEX "idx_contact_bic_contact_id" ON public."contact_broader_impact_categories"(contact_id);
CREATE INDEX "idx_contact_bic_category_id" ON public."contact_broader_impact_categories"(broader_impact_category_id);
CREATE INDEX "idx_project_bic_project_id" ON public."project_broader_impact_categories"(project_id);
CREATE INDEX "idx_project_bic_category_id" ON public."project_broader_impact_categories"(broader_impact_category_id);

-- =====================================================
-- PRIMARY KEY CONSTRAINTS
-- =====================================================

ALTER TABLE "public"."organization_types" ADD CONSTRAINT "organization_types_pkey" PRIMARY KEY USING INDEX "organization_types_pkey";
ALTER TABLE "public"."organizations" ADD CONSTRAINT "organizations_pkey" PRIMARY KEY USING INDEX "organizations_pkey";
ALTER TABLE "public"."contacts" ADD CONSTRAINT "contacts_pkey" PRIMARY KEY USING INDEX "contacts_pkey";
ALTER TABLE "public"."project_statuses" ADD CONSTRAINT "project_statuses_pkey" PRIMARY KEY USING INDEX "project_statuses_pkey";
ALTER TABLE "public"."interest_centers" ADD CONSTRAINT "interest_centers_pkey" PRIMARY KEY USING INDEX "interest_centers_pkey";
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_pkey" PRIMARY KEY USING INDEX "projects_pkey";
ALTER TABLE "public"."broader_impact_categories" ADD CONSTRAINT "broader_impact_categories_pkey" PRIMARY KEY USING INDEX "broader_impact_categories_pkey";

-- =====================================================
-- FOREIGN KEY CONSTRAINTS
-- =====================================================

-- Organizations foreign keys
ALTER TABLE "public"."organizations" ADD CONSTRAINT "organizations_organization_type_id_fkey"
  FOREIGN KEY (organization_type_id) REFERENCES organization_types(id) NOT VALID;
ALTER TABLE "public"."organizations" VALIDATE CONSTRAINT "organizations_organization_type_id_fkey";

-- Contacts foreign keys
ALTER TABLE "public"."contacts" ADD CONSTRAINT "contacts_organization_id_fkey"
  FOREIGN KEY (organization_id) REFERENCES organizations(id) NOT VALID;
ALTER TABLE "public"."contacts" VALIDATE CONSTRAINT "contacts_organization_id_fkey";

-- Projects foreign keys
ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_organization_id_fkey"
  FOREIGN KEY (organization_id) REFERENCES organizations(id) NOT VALID;
ALTER TABLE "public"."projects" VALIDATE CONSTRAINT "projects_organization_id_fkey";

ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_interest_center_id_fkey"
  FOREIGN KEY (interest_center_id) REFERENCES interest_centers(id) NOT VALID;
ALTER TABLE "public"."projects" VALIDATE CONSTRAINT "projects_interest_center_id_fkey";

ALTER TABLE "public"."projects" ADD CONSTRAINT "projects_status_id_fkey"
  FOREIGN KEY (status_id) REFERENCES project_statuses(id) NOT VALID;
ALTER TABLE "public"."projects" VALIDATE CONSTRAINT "projects_status_id_fkey";

-- Junction table foreign keys (with CASCADE delete for proper cleanup)
ALTER TABLE "public"."organization_broader_impact_categories" ADD CONSTRAINT "org_bic_organization_fkey"
  FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."organization_broader_impact_categories" VALIDATE CONSTRAINT "org_bic_organization_fkey";

ALTER TABLE "public"."organization_broader_impact_categories" ADD CONSTRAINT "org_bic_category_fkey"
  FOREIGN KEY (broader_impact_category_id) REFERENCES broader_impact_categories(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."organization_broader_impact_categories" VALIDATE CONSTRAINT "org_bic_category_fkey";

ALTER TABLE "public"."contact_projects" ADD CONSTRAINT "contact_projects_contact_fkey"
  FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."contact_projects" VALIDATE CONSTRAINT "contact_projects_contact_fkey";

ALTER TABLE "public"."contact_projects" ADD CONSTRAINT "contact_projects_project_fkey"
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."contact_projects" VALIDATE CONSTRAINT "contact_projects_project_fkey";

ALTER TABLE "public"."contact_broader_impact_categories" ADD CONSTRAINT "contact_bic_contact_fkey"
  FOREIGN KEY (contact_id) REFERENCES contacts(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."contact_broader_impact_categories" VALIDATE CONSTRAINT "contact_bic_contact_fkey";

ALTER TABLE "public"."contact_broader_impact_categories" ADD CONSTRAINT "contact_bic_category_fkey"
  FOREIGN KEY (broader_impact_category_id) REFERENCES broader_impact_categories(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."contact_broader_impact_categories" VALIDATE CONSTRAINT "contact_bic_category_fkey";

ALTER TABLE "public"."project_broader_impact_categories" ADD CONSTRAINT "project_bic_project_fkey"
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."project_broader_impact_categories" VALIDATE CONSTRAINT "project_bic_project_fkey";

ALTER TABLE "public"."project_broader_impact_categories" ADD CONSTRAINT "project_bic_category_fkey"
  FOREIGN KEY (broader_impact_category_id) REFERENCES broader_impact_categories(id) ON DELETE CASCADE NOT VALID;
ALTER TABLE "public"."project_broader_impact_categories" VALIDATE CONSTRAINT "project_bic_category_fkey";

-- =====================================================
-- GRANT PERMISSIONS
-- =====================================================
-- Note: Admin role gets full CRUD, user/collaborator roles get read-only access
-- RLS policies in 02_broader_impacts_permissions.sql enforce this

-- Core entity tables
GRANT SELECT ON TABLE "public"."organization_types" TO web_anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."organization_types" TO authenticated;

GRANT SELECT ON TABLE "public"."organizations" TO web_anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."organizations" TO authenticated;

GRANT SELECT ON TABLE "public"."contacts" TO web_anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."contacts" TO authenticated;

GRANT SELECT ON TABLE "public"."project_statuses" TO web_anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."project_statuses" TO authenticated;

GRANT SELECT ON TABLE "public"."interest_centers" TO web_anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."interest_centers" TO authenticated;

GRANT SELECT ON TABLE "public"."projects" TO web_anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."projects" TO authenticated;

GRANT SELECT ON TABLE "public"."broader_impact_categories" TO web_anon, authenticated;
GRANT INSERT, UPDATE, DELETE ON TABLE "public"."broader_impact_categories" TO authenticated;

-- Junction tables (no UPDATE needed, only INSERT/DELETE for M:M relationships)
GRANT SELECT, INSERT, DELETE ON TABLE "public"."organization_broader_impact_categories" TO web_anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE "public"."contact_projects" TO web_anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE "public"."contact_broader_impact_categories" TO web_anon, authenticated;
GRANT SELECT, INSERT, DELETE ON TABLE "public"."project_broader_impact_categories" TO web_anon, authenticated;

-- =====================================================
-- GRANT SEQUENCE PERMISSIONS
-- =====================================================

GRANT USAGE ON SEQUENCE "public"."organization_types_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."organizations_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."contacts_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."project_statuses_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."interest_centers_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."projects_id_seq" TO web_anon, authenticated;
GRANT USAGE ON SEQUENCE "public"."broader_impact_categories_id_seq" TO web_anon, authenticated;

-- =====================================================
-- ENABLE ROW LEVEL SECURITY
-- =====================================================

ALTER TABLE "public"."organization_types" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."organizations" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contacts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_statuses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."interest_centers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."broader_impact_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."organization_broader_impact_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contact_projects" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."contact_broader_impact_categories" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."project_broader_impact_categories" ENABLE ROW LEVEL SECURITY;

-- =====================================================
-- TIMESTAMP TRIGGERS
-- =====================================================

-- organization_types triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."organization_types"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."organization_types"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- organizations triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."organizations"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."organizations"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- contacts triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."contacts"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."contacts"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- project_statuses triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."project_statuses"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."project_statuses"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- interest_centers triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."interest_centers"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."interest_centers"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- projects triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."projects"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."projects"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- broader_impact_categories triggers
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."broader_impact_categories"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_updated_at_trigger
  BEFORE INSERT OR UPDATE ON public."broader_impact_categories"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

-- Junction tables (only created_at triggers, no updated_at needed)
CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."organization_broader_impact_categories"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."contact_projects"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."contact_broader_impact_categories"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

CREATE TRIGGER set_created_at_trigger
  BEFORE INSERT ON public."project_broader_impact_categories"
  FOR EACH ROW
  EXECUTE FUNCTION public.set_created_at();

-- =====================================================
-- NOTIFY POSTGREST
-- =====================================================

NOTIFY pgrst, 'reload schema';

-- Source: 02_broader_impacts_permissions.sql

-- =====================================================
-- Broader Impacts Tracking System - Permissions
-- =====================================================
-- This file defines Row Level Security (RLS) policies for all tables
-- Permission Model:
--   - anonymous: No access to tables
--   - user: Read-only access
--   - collaborator: Read-only access (can be enhanced later for field-level differences)
--   - admin: Full CRUD access

-- =====================================================
-- ENSURE COLLABORATOR ROLE EXISTS
-- =====================================================

-- Insert collaborator role if it doesn't exist
INSERT INTO metadata.roles (display_name, description)
SELECT 'collaborator', 'Collaborator with full read access to all data'
WHERE NOT EXISTS (
  SELECT 1 FROM metadata.roles WHERE display_name = 'collaborator'
);

-- Note: This deployment uses existing Civic OS RBAC functions:
--   - public.get_user_roles() - returns array of role names
--   - public.is_admin() - checks if user has admin role
--   - public.has_permission(table_name, permission) - checks table-level permissions

-- =====================================================
-- RLS POLICIES: ORGANIZATION TYPES
-- =====================================================

CREATE POLICY "organization_types: read permission" ON "public"."organization_types"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('organization_types', 'read'));

CREATE POLICY "organization_types: create permission" ON "public"."organization_types"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('organization_types', 'create'));

CREATE POLICY "organization_types: update permission" ON "public"."organization_types"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('organization_types', 'update'))
  WITH CHECK (public.has_permission('organization_types', 'update'));

CREATE POLICY "organization_types: delete permission" ON "public"."organization_types"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('organization_types', 'delete'));

-- =====================================================
-- RLS POLICIES: ORGANIZATIONS
-- =====================================================

CREATE POLICY "organizations: read permission" ON "public"."organizations"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('organizations', 'read'));

CREATE POLICY "organizations: create permission" ON "public"."organizations"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('organizations', 'create'));

CREATE POLICY "organizations: update permission" ON "public"."organizations"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('organizations', 'update'))
  WITH CHECK (public.has_permission('organizations', 'update'));

CREATE POLICY "organizations: delete permission" ON "public"."organizations"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('organizations', 'delete'));

-- =====================================================
-- RLS POLICIES: CONTACTS
-- =====================================================

CREATE POLICY "contacts: read permission" ON "public"."contacts"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('contacts', 'read'));

CREATE POLICY "contacts: create permission" ON "public"."contacts"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('contacts', 'create'));

CREATE POLICY "contacts: update permission" ON "public"."contacts"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('contacts', 'update'))
  WITH CHECK (public.has_permission('contacts', 'update'));

CREATE POLICY "contacts: delete permission" ON "public"."contacts"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('contacts', 'delete'));

-- =====================================================
-- RLS POLICIES: PROJECT STATUSES
-- =====================================================

CREATE POLICY "project_statuses: read permission" ON "public"."project_statuses"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('project_statuses', 'read'));

CREATE POLICY "project_statuses: create permission" ON "public"."project_statuses"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('project_statuses', 'create'));

CREATE POLICY "project_statuses: update permission" ON "public"."project_statuses"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('project_statuses', 'update'))
  WITH CHECK (public.has_permission('project_statuses', 'update'));

CREATE POLICY "project_statuses: delete permission" ON "public"."project_statuses"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('project_statuses', 'delete'));

-- =====================================================
-- RLS POLICIES: INTEREST CENTERS
-- =====================================================

CREATE POLICY "interest_centers: read permission" ON "public"."interest_centers"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('interest_centers', 'read'));

CREATE POLICY "interest_centers: create permission" ON "public"."interest_centers"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('interest_centers', 'create'));

CREATE POLICY "interest_centers: update permission" ON "public"."interest_centers"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('interest_centers', 'update'))
  WITH CHECK (public.has_permission('interest_centers', 'update'));

CREATE POLICY "interest_centers: delete permission" ON "public"."interest_centers"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('interest_centers', 'delete'));

-- =====================================================
-- RLS POLICIES: PROJECTS
-- =====================================================

CREATE POLICY "projects: read permission" ON "public"."projects"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('projects', 'read'));

CREATE POLICY "projects: create permission" ON "public"."projects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('projects', 'create'));

CREATE POLICY "projects: update permission" ON "public"."projects"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('projects', 'update'))
  WITH CHECK (public.has_permission('projects', 'update'));

CREATE POLICY "projects: delete permission" ON "public"."projects"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('projects', 'delete'));

-- =====================================================
-- RLS POLICIES: BROADER IMPACT CATEGORIES
-- =====================================================

CREATE POLICY "broader_impact_categories: read permission" ON "public"."broader_impact_categories"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('broader_impact_categories', 'read'));

CREATE POLICY "broader_impact_categories: create permission" ON "public"."broader_impact_categories"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('broader_impact_categories', 'create'));

CREATE POLICY "broader_impact_categories: update permission" ON "public"."broader_impact_categories"
  FOR UPDATE
  TO PUBLIC
  USING (public.has_permission('broader_impact_categories', 'update'))
  WITH CHECK (public.has_permission('broader_impact_categories', 'update'));

CREATE POLICY "broader_impact_categories: delete permission" ON "public"."broader_impact_categories"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('broader_impact_categories', 'delete'));

-- =====================================================
-- RLS POLICIES: ORGANIZATION <-> BROADER IMPACT CATEGORIES
-- =====================================================

CREATE POLICY "org_bic: read permission" ON "public"."organization_broader_impact_categories"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('organization_broader_impact_categories', 'read'));

CREATE POLICY "org_bic: create permission" ON "public"."organization_broader_impact_categories"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('organization_broader_impact_categories', 'create'));

CREATE POLICY "org_bic: delete permission" ON "public"."organization_broader_impact_categories"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('organization_broader_impact_categories', 'delete'));

-- =====================================================
-- RLS POLICIES: CONTACT <-> PROJECTS
-- =====================================================

CREATE POLICY "contact_projects: read permission" ON "public"."contact_projects"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('contact_projects', 'read'));

CREATE POLICY "contact_projects: create permission" ON "public"."contact_projects"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('contact_projects', 'create'));

CREATE POLICY "contact_projects: delete permission" ON "public"."contact_projects"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('contact_projects', 'delete'));

-- =====================================================
-- RLS POLICIES: CONTACT <-> BROADER IMPACT CATEGORIES
-- =====================================================

CREATE POLICY "contact_bic: read permission" ON "public"."contact_broader_impact_categories"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('contact_broader_impact_categories', 'read'));

CREATE POLICY "contact_bic: create permission" ON "public"."contact_broader_impact_categories"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('contact_broader_impact_categories', 'create'));

CREATE POLICY "contact_bic: delete permission" ON "public"."contact_broader_impact_categories"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('contact_broader_impact_categories', 'delete'));

-- =====================================================
-- RLS POLICIES: PROJECT <-> BROADER IMPACT CATEGORIES
-- =====================================================

CREATE POLICY "project_bic: read permission" ON "public"."project_broader_impact_categories"
  FOR SELECT
  TO PUBLIC
  USING (public.has_permission('project_broader_impact_categories', 'read'));

CREATE POLICY "project_bic: create permission" ON "public"."project_broader_impact_categories"
  FOR INSERT
  TO PUBLIC
  WITH CHECK (public.has_permission('project_broader_impact_categories', 'create'));

CREATE POLICY "project_bic: delete permission" ON "public"."project_broader_impact_categories"
  FOR DELETE
  TO PUBLIC
  USING (public.has_permission('project_broader_impact_categories', 'delete'));

-- Source: 03_broader_impacts_data.sql

-- =====================================================
-- Broader Impacts Tracking System - Seed Data & Metadata
-- =====================================================
-- This file contains:
-- 1. Seed data for lookup tables
-- 2. Sample data for core entities
-- 3. Metadata configuration for UI customization
-- 4. Permission configuration

-- =====================================================
-- SEED DATA: ORGANIZATION TYPES
-- =====================================================

INSERT INTO public.organization_types (display_name, description) VALUES
  ('Academic', 'Universities, colleges, and research institutions'),
  ('Non-Profit', 'Non-profit organizations and NGOs'),
  ('Government', 'Government agencies and departments'),
  ('Corporate', 'For-profit companies and corporations'),
  ('Foundation', 'Philanthropic foundations and grant-making organizations');

-- =====================================================
-- SEED DATA: PROJECT STATUSES
-- =====================================================

INSERT INTO public.project_statuses (display_name, description) VALUES
  ('Planning', 'Project is in the planning phase'),
  ('Active', 'Project is currently active and ongoing'),
  ('Completed', 'Project has been successfully completed'),
  ('On Hold', 'Project is temporarily paused'),
  ('Cancelled', 'Project has been cancelled');

-- =====================================================
-- SEED DATA: INTEREST CENTERS
-- =====================================================

INSERT INTO public.interest_centers (display_name, description) VALUES
  ('Education & Outreach', 'Educational programs and community outreach initiatives'),
  ('Environmental Sustainability', 'Environmental conservation and sustainability projects'),
  ('Health & Wellness', 'Public health and wellness programs'),
  ('Economic Development', 'Economic growth and development initiatives'),
  ('Social Justice', 'Social equity and justice programs'),
  ('Arts & Culture', 'Cultural preservation and arts programs'),
  ('Technology & Innovation', 'Technological advancement and innovation projects'),
  ('Community Building', 'Community engagement and development initiatives');

-- =====================================================
-- SEED DATA: BROADER IMPACT CATEGORIES
-- =====================================================

INSERT INTO public.broader_impact_categories (display_name, description) VALUES
  ('K-12 Education', 'Programs targeting K-12 students and educators'),
  ('Undergraduate Education', 'Undergraduate student engagement and learning'),
  ('Graduate Education', 'Graduate student training and development'),
  ('Public Engagement', 'Engagement with the general public'),
  ('Diversity & Inclusion', 'Promoting diversity, equity, and inclusion'),
  ('Climate Change', 'Addressing climate change and adaptation'),
  ('Economic Opportunity', 'Creating economic opportunities and jobs'),
  ('Health Equity', 'Promoting health equity and access'),
  ('Environmental Justice', 'Environmental justice and equity'),
  ('STEM Workforce', 'Building the STEM workforce pipeline'),
  ('Policy Impact', 'Influencing public policy and decision-making'),
  ('International Collaboration', 'Cross-border and international partnerships'),
  ('Rural Communities', 'Supporting rural and underserved communities'),
  ('Urban Development', 'Urban planning and community development'),
  ('Indigenous Knowledge', 'Incorporating and preserving indigenous knowledge');

-- =====================================================
-- METADATA: ENTITIES CONFIGURATION
-- =====================================================

INSERT INTO metadata.entities (table_name, display_name, description, sort_order) VALUES
  ('organizations', 'Organizations', 'Organizations and institutions involved in broader impacts work', 10),
  ('contacts', 'Contacts', 'Individual contacts and collaborators', 20),
  ('projects', 'Projects', 'Research and engagement projects', 30),
  ('interest_centers', 'Interest Centers', 'Areas of focus and interest', 40),
  ('broader_impact_categories', 'Impact Categories', 'Categories of broader societal impact', 50),
  ('organization_types', 'Organization Types', 'Types of organizations (lookup table)', 60),
  ('project_statuses', 'Project Statuses', 'Project status values (lookup table)', 70)
ON CONFLICT (table_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- =====================================================
-- METADATA: PROPERTIES CONFIGURATION
-- =====================================================

-- Organizations properties
INSERT INTO metadata.properties (table_name, column_name, display_name, description, sort_order, show_on_list, show_on_create) VALUES
  ('organizations', 'display_name', 'Organization Name', 'Name of the organization', 1, true, true),
  ('organizations', 'organization_type_id', 'Type', 'Type of organization', 2, true, true),
  ('organizations', 'email', 'Email', 'Contact email address', 3, true, true),
  ('organizations', 'phone', 'Phone', 'Contact phone number', 4, true, true),
  ('organizations', 'website', 'Website', 'Organization website URL', 5, true, true),
  ('organizations', 'address', 'Address', 'Physical address', 6, false, true),
  ('organizations', 'description', 'Description', 'Description of the organization', 7, false, true)
ON CONFLICT (table_name, column_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- Contacts properties
INSERT INTO metadata.properties (table_name, column_name, display_name, description, sort_order, show_on_list, show_on_create) VALUES
  ('contacts', 'first_name', 'First Name', 'Contact first name', 1, true, true),
  ('contacts', 'last_name', 'Last Name', 'Contact last name', 2, true, true),
  ('contacts', 'email', 'Email', 'Email address', 3, true, true),
  ('contacts', 'phone', 'Phone', 'Phone number', 4, true, true),
  ('contacts', 'organization_id', 'Organization', 'Associated organization', 5, true, true),
  ('contacts', 'title', 'Title', 'Job title or position', 6, false, true),
  ('contacts', 'description', 'Description', 'Additional information about the contact', 7, false, true)
ON CONFLICT (table_name, column_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- Projects properties
INSERT INTO metadata.properties (table_name, column_name, display_name, description, sort_order, show_on_list, show_on_create) VALUES
  ('projects', 'display_name', 'Project Name', 'Name of the project', 1, true, true),
  ('projects', 'organization_id', 'Organization', 'Lead organization', 2, true, true),
  ('projects', 'status_id', 'Status', 'Current project status', 3, true, true),
  ('projects', 'interest_center_id', 'Interest Center', 'Primary area of focus', 4, true, true),
  ('projects', 'start_date', 'Start Date', 'Project start date', 5, true, true),
  ('projects', 'end_date', 'End Date', 'Project end date', 6, true, true),
  ('projects', 'description', 'Description', 'Detailed project description', 7, false, true)
ON CONFLICT (table_name, column_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- Interest Centers properties
INSERT INTO metadata.properties (table_name, column_name, display_name, description, sort_order, show_on_list, show_on_create) VALUES
  ('interest_centers', 'display_name', 'Name', 'Interest center name', 1, true, true),
  ('interest_centers', 'description', 'Description', 'Description of this interest area', 2, true, true)
ON CONFLICT (table_name, column_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- Broader Impact Categories properties
INSERT INTO metadata.properties (table_name, column_name, display_name, description, sort_order, show_on_list, show_on_create) VALUES
  ('broader_impact_categories', 'display_name', 'Category Name', 'Impact category name', 1, true, true),
  ('broader_impact_categories', 'description', 'Description', 'Description of this impact category', 2, true, true)
ON CONFLICT (table_name, column_name) DO UPDATE
  SET display_name = EXCLUDED.display_name,
      description = EXCLUDED.description,
      sort_order = EXCLUDED.sort_order;

-- =====================================================
-- PERMISSIONS CONFIGURATION
-- =====================================================

-- Create permission entries for all tables
INSERT INTO metadata.permissions (table_name, permission)
SELECT t.table_name, p.permission::metadata.permission
FROM (VALUES
  ('organizations'),
  ('contacts'),
  ('projects'),
  ('interest_centers'),
  ('broader_impact_categories'),
  ('organization_types'),
  ('project_statuses'),
  ('organization_broader_impact_categories'),
  ('contact_projects'),
  ('contact_broader_impact_categories'),
  ('project_broader_impact_categories')
) AS t(table_name)
CROSS JOIN (VALUES ('create'), ('read'), ('update'), ('delete')) AS p(permission)
ON CONFLICT (table_name, permission) DO NOTHING;

-- Assign READ permissions to user and collaborator roles
INSERT INTO metadata.permission_roles (permission_id, role_id)
SELECT p.id, r.id
FROM metadata.permissions p
CROSS JOIN metadata.roles r
WHERE p.permission = 'read'
  AND r.display_name IN ('user', 'collaborator')
ON CONFLICT (permission_id, role_id) DO NOTHING;

-- Assign FULL permissions to admin role
INSERT INTO metadata.permission_roles (permission_id, role_id)
SELECT p.id, r.id
FROM metadata.permissions p
CROSS JOIN metadata.roles r
WHERE r.display_name = 'admin'
ON CONFLICT (permission_id, role_id) DO NOTHING;

-- =====================================================
-- NOTIFY POSTGREST
-- =====================================================

NOTIFY pgrst, 'reload schema';

-- Source: 04_broader_impacts_search.sql

-- =====================================================
-- Broader Impacts Tracking System - Full-Text Search
-- =====================================================
-- This file adds full-text search capabilities to organizations, contacts, and projects
-- using PostgreSQL's tsvector and GIN indexes

-- =====================================================
-- ADD TEXT SEARCH COLUMN TO ORGANIZATIONS
-- =====================================================

ALTER TABLE public.organizations
ADD COLUMN civic_os_text_search tsvector
GENERATED ALWAYS AS (
  to_tsvector('english',
    coalesce(display_name, '') || ' ' ||
    coalesce(description, '')
  )
) STORED;

-- Create GIN index for fast full-text search
CREATE INDEX idx_organizations_text_search
ON public.organizations
USING gin(civic_os_text_search);

-- Configure search fields in metadata
UPDATE metadata.entities
SET search_fields = ARRAY['display_name', 'description']
WHERE table_name = 'organizations';

-- =====================================================
-- ADD TEXT SEARCH COLUMN TO CONTACTS
-- =====================================================

ALTER TABLE public.contacts
ADD COLUMN civic_os_text_search tsvector
GENERATED ALWAYS AS (
  to_tsvector('english',
    coalesce(first_name, '') || ' ' ||
    coalesce(last_name, '') || ' ' ||
    coalesce(email, '')
  )
) STORED;

-- Create GIN index for fast full-text search
CREATE INDEX idx_contacts_text_search
ON public.contacts
USING gin(civic_os_text_search);

-- Configure search fields in metadata
UPDATE metadata.entities
SET search_fields = ARRAY['first_name', 'last_name', 'email']
WHERE table_name = 'contacts';

-- =====================================================
-- ADD TEXT SEARCH COLUMN TO PROJECTS
-- =====================================================

ALTER TABLE public.projects
ADD COLUMN civic_os_text_search tsvector
GENERATED ALWAYS AS (
  to_tsvector('english',
    coalesce(display_name, '') || ' ' ||
    coalesce(description, '')
  )
) STORED;

-- Create GIN index for fast full-text search
CREATE INDEX idx_projects_text_search
ON public.projects
USING gin(civic_os_text_search);

-- Configure search fields in metadata
UPDATE metadata.entities
SET search_fields = ARRAY['display_name', 'description']
WHERE table_name = 'projects';

-- =====================================================
-- NOTIFY POSTGREST
-- =====================================================

NOTIFY pgrst, 'reload schema';

-- Source: 05_broader_impacts_dashboard.sql

-- =====================================================
-- Broader Impacts Tracking System - Custom Dashboard
-- =====================================================
-- This file customizes the default dashboard for the Broader Impacts deployment

-- Update the default "Welcome" dashboard to be specific to Broader Impacts
UPDATE metadata.dashboards
SET display_name = 'Broader Impacts Dashboard',
    description = 'Track organizations, contacts, projects, and their broader societal impact'
WHERE is_default = TRUE;

-- Update the welcome widget with Broader Impacts-specific content
UPDATE metadata.dashboard_widgets
SET config = jsonb_build_object(
  'content', E'# Broader Impacts Tracking System\n\nThis system helps you track and manage **organizations, contacts, projects, and their broader societal impact categories** — enabling comprehensive collaboration and impact assessment across academic, non-profit, government, and corporate partnerships.\n\n## What You Can Track\n\n- **Organizations** - Academic institutions, non-profits, government agencies, corporations, and foundations\n- **Contacts** - Individual collaborators and project contributors\n- **Projects** - Research and engagement initiatives with start/end dates and status tracking\n- **Interest Centers** - Areas of focus (Education, Environment, Health, Economic Development, etc.)\n- **Impact Categories** - NSF-style broader impact classifications (K-12 Education, STEM Workforce, Climate Change, etc.)\n\n## Key Features\n\n- 🔍 **Full-Text Search** - Quickly find organizations, contacts, and projects\n- 🔗 **Many-to-Many Relationships** - Tag organizations, contacts, and projects with multiple impact categories\n- 👥 **Collaboration Tracking** - Link contacts to multiple projects\n- 📊 **Rich Metadata** - Descriptions, types, statuses, and dates for comprehensive tracking\n\n## Getting Started\n\n1. **Browse Entities** - Use the menu to explore organizations, contacts, and projects\n2. **Search** - Use the search bar on list pages to find specific records\n3. **View Relationships** - Click on any record to see related entities (e.g., all projects for an organization)\n4. **Admin Functions** - Admins can create new records and manage the system\n\n## Permission Levels\n\n- **User/Collaborator** - Read-only access to all data\n- **Admin** - Full access to create, edit, and delete records\n\n---\n\n*Ready to explore? Start by browsing **Organizations** or **Projects** from the menu above.*',
  'enableHtml', false
)
WHERE dashboard_id = (SELECT id FROM metadata.dashboards WHERE is_default = TRUE)
  AND widget_type = 'markdown';

-- Notify PostgREST to reload schema cache
NOTIFY pgrst, 'reload schema';

-- =============================================================================================================
-- SETUP COMPLETE
-- =============================================================================================================

-- Next steps:
-- 1. Review this SQL file
-- 2. Execute against your hosted database:
--    psql 'postgresql://user:password@host:port/dbname?sslmode=require' -f umflint-bi.sql

